INTERPOLATION_MARKER = '$'
IMPORT_INTERPOLATION_MARKER = '@'
INTERPOLATION_BLOCK_END = '$'
IMPORT_DATA_SEPARATOR = ':'
IMPORT_LINE_SEPARATOR = ' '
WEIGHTED_CHOICE_SEPARATOR = ' '
GENERATOR_IMPORT_KEYWORD = 'generator'
RESOURCE_IMPORT_KEYWORD = 'resource'
IMPORT_ITPL_END = ' '
IMPORT_ITPL_OPEN_DELIMITER = '{'
IMPORT_ITPL_CLOSE_DELIMITER = '}'
CHOICE_EXPRESSION_END = '\n'

COMMAND_EXPRESSION_MARKER = '#'
COMMAND_EXPRESSION_OPEN_DELIMITER = '('
COMMAND_EXPRESSION_CLOSE_DELIMITER = ')'
COMMAND_ARGUMENT_SEPARATOR = ','

CHOICE_EXPRESSION_CONTROL_MARKERS = [INTERPOLATION_MARKER, IMPORT_INTERPOLATION_MARKER]
TEXT_EXPRESSION_CONTROL_MARKERS = [COMMAND_EXPRESSION_MARKER]


GENERATOR_PARSER = 'generator'
RESOURCE_PARSER = 'resouce'